scrnah5adscvi2leidensbyresolution:
  condaenv: u_scvi
  label:
  - resolution_1
  - resolution_2
  resolution_1:
  - 0.3
  resolution_2:
  - 0.01
  - 0.02
  - 0.03
  - 0.04
  - 0.05
  - 0.06
  - 0.07
  - 0.08
  - 0.09
  - 0.1
  - 0.2
  - 0.3
  - 0.4
  - 0.5
  - 0.6
  - 0.7
  - 0.8
  - 0.9
  - 1.0
  seed: 12345
