rmatrix2normheatmap:
  key:
  - leiden
  - leiden_0
  - leiden_1
  label:
  - sampleid
  - donor
  height: 7.5
  width: 10
  size: 5
  angle: 90
  display:
  - T
  - C
scrnascanpypldotplot:
  height: 8
  width: 8
  group:
  - leiden
  - leiden_0
  - leiden_1
  norm: true
  dendrogram: true
  marker: /storage/chen/home/u236923/.local/jinliwrapper/src/retinamarkermajortype/data/hs_RGC.txt.gz
scrnascanpyplviolin:
  height: 5
  width: 10
  group:
  - leiden
  - leiden_0
  - leiden_1
  key:
  - nCount_RNA
  - nFeature_RNA
  - pANN
  - percent.mt
  norm: true
  angle: 90
scrnah5adumapby:
  condaenv: null
  width: 5
  height: 5
  label:
  - sampleid
  - leiden
  - leiden_0
  - leiden_1
  - nCount_RNA
  - nFeature_RNA
  - percent.mt
scrnah5ad2tlrankgenesgroups:
  condaenv: null
  group:
  - leiden
  - leiden_0
  - leiden_1
  ngene: 100
  hvg: true
  batchkey: sampleid
  ntop: 10000
  flavor: seurat
  ntoprank: 20
  marker: /storage/chen/home/u236923/.local/jinliwrapper/src/merscopegenes/data/v2//hs.txt.gz
scrnah5ad2normscale:
  condaenv: null
  scale: false
scrnah5adfeatureplotumap:
  width: 5
  height: 5
  feature:
  - RBPMS
  - SLC17A6
  - NEFL
  - POU4F1
  - POU4F2
  - THY1
  - TPBG
  - TBR1
  - CA8
  - CHRNA2
  - KCNA1
  - OPN4
  - SATB2
  - BNC2
  - FOXP2
  norm: true
scrnah5adscvi2sccaf:
  skip: false
  condaenv: sccaf
  key:
  - leiden_1
  catcode:
  - leiden_1
  acc:
  - 0.95
  - 0.98
  seed: 12345
  numthreads: 16
